### ISSUE TITLE
Import conflict with django-compressor

### ISSUE THREAD

**Issue by ghost** [django-guardian/django-guardian#161]
ImportError: No module named guardiancompressor

Django: 1.6b1, 1.5, 1.4 (probably also others)
Python 2.7.3
django-compressor 1.3
django-guardian 1.1.1

UPDATE:
Removing "compressor" (django compressor) from installed_apps solves the issue, so I'm guessing django compressor has some module with the same name, causing the error.

**Comment by amberdiehl** [comment]
Actually, I had a similar problem only it was "No module named gardianstorages". The issue was that I forgot to add the comma after adding "guardian" to my apps. Needless to say, the following app was 'storages' and since there was no comma separating them, Django was trying to load the app 'gardianstorages'. Basic mistake--I figure it's worth mentioning since someone else did the same thing and the fix was a comma, not removing an app.
