### ISSUE TITLE
Direct foreign key for more than one model clashes on related name for user, group and permissions

### ISSUE THREAD

**Issue by loop0** [django-guardian/django-guardian#210]
Because of the use of inheritance of UserObjectPermissionBase and GroupObjectPermissionBase for direct foreign key in models the django/south gives me these errors:

```sh
Accessor for field 'user' clashes with related field 'User.groupuserobjectpermission_set'. Add a related_name argument to the definition for 'user'.
Accessor for field 'group' clashes with related field 'Group.groupgroupobjectpermission_set'. Add a related_name argument to the definition for 'group'.
Accessor for field 'permission' clashes with related field 'Permission.groupuserobjectpermission_set'. Add a related_name argument to the definition for 'permission'.
```

I was able to circumvent this problem by editing guardian/models.py and adding: related_name='+' to respective foreign keys of user, group and permission, but I'm not really aware if this can brake the rest of django-guardian. I can work on a fix if someone can give me some light here.

Thanks!

**Comment by brianmay** [comment]
Any news?

I suspect that the Direct FK can only be used on one model; it doesn't look like this is going to change anytime soon (PR welcome however).

So I will mark this as a documentation issue, as I suspect this limitation isn't correctly documented.

**Comment by loop0** [comment]
To be honest, I never revisited this issue again. I can't remember how it was fixed in my side. :(

**Comment by niekbaeten** [comment]
The documentation is wrong, there's no limitation on the amount of models with a Direct FK. We have multiple models using it. The issue might be with duplicate model names over apps.

**Comment by brianmay** [comment]
I may have been two quick to diagnose this, looks like @niekbaeten is right - there shouldn't be any clash between the related fields. I am going to reopen this bug, revert my change to the documentation, and then close this bug.

As a concrete example, if I enabled this for the testapp project by creating a Proposal type and a Project type, the user has two additional attributes: projectuserobjectpermission_set and proposaluserobjectpermission_set. I don't see any clash between the two.

Unfortunately there isn't enough information given to diagnose the problem. It is possible this is something that has been fixed in Django too.
