### ISSUE TITLE
Any staff user can gain permissions

### ISSUE THREAD

**Issue by Sovetnikov** [django-guardian/django-guardian#305]
Guardian admin views for managing object permissions does not check for user permission to make any changes in admin site.
Any user logged in to admin site can access URL like http://127.0.0.1:8080/admin/main/complex/2/permissions/ and give change permissions to himself.
Hows that possible?
I'm using Django 1.7.7, guardian 1.2.5 with python 3.4

**Comment by Sovetnikov** [comment]
Monkey patch to require 'guardina:userobjectpermission_change' permission to access any guardian view:
from django.contrib.auth import get_permission_codename
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from guardian.admin import GuardedModelAdminMixin
from guardian.models import UserObjectPermission

def guardian_perm_decorator(func):
    def _decorated(*args, **kwargs):
        self = args[0]
        request = args[1]

        opts = UserObjectPermission._meta
        codename = get_permission_codename('change', opts)
        if request.user.has_perm("%s.%s" % (opts.app_label, codename), ):
            return func(*args, **kwargs)
        raise PermissionDenied
    return _decorated

GuardedModelAdminMixin.obj_perms_manage_view = guardian_perm_decorator(GuardedModelAdminMixin.obj_perms_manage_view)
GuardedModelAdminMixin.obj_perms_manage_user_view = guardian_perm_decorator(GuardedModelAdminMixin.obj_perms_manage_user_view)
GuardedModelAdminMixin.obj_perms_manage_group_view = guardian_perm_decorator(GuardedModelAdminMixin.obj_perms_manage_group_view)

**Comment by philippeluickx** [comment]
+1
I didn't really get this... any staff user can change permissions on object level?

@Sovetnikov thanks for the patch!

**Comment by brianmay** [comment]
This bug report, if I understand correctly, is that anybody who has access to the admin view (by setting is_staff and not setting is_superuser) can access everything without regard to the guardian permissions.

**Comment by lukaszb** [comment]
Yeah, this is how it works. I mean, in order to handle object level permissions for users at admin there is not much currently guardian helps with. This is, however, not a bug, it might just not be marketed properly at the docs.

So, to answer, guardian is there to help you build such object lever permission checks at the admin panel or your app. Does not magically assume package users intentions.

OTOH, it's our fault not being explicit about this at the docs. Any idea where/how we can make the docs better?

**Comment by Sovetnikov** [comment]
You offer just mark that in DOCS? Great thing!
Just make this check!
For super user permissions or your custom permission or for change permission.
Any verification is reasonable.

**Comment by brianmay** [comment]
@lukaszb Just to aid my understanding, what would break if we were to include the permission checks directly in `GuardedModelAdminMixin`? Can you give an example of an application that would break with these checks?

My personal opinion: I generally use the admin site only for people who have access to everything already. I don't like exposing it to non-admin people - it is far too limiting. However I believe it does have global permission checks already built in...

@Sovetnikov Not sure why you resorted to monkey patching. I would have thought a cleaner solution would be to make a new class derived from `GuardedModelAdmin` and override the required functions.

If anybody wants to demonstrate how this could be fixed, there is now a working `example_project` included with django-guardian source that should be usable for the purpose.

**Comment by Sovetnikov** [comment]
@brianmay You asking me why Django has system of permissions, and why it is reasonable to support it?
Guardian itself making object level permissions work.
Why any staff user must gain access to all objects by default?
Staff user can be just a manager that only can add a news or it can be limited time employed freelancer for specific work.

**Comment by brianmay** [comment]
Testing this using the `example_project`, it seems that Django admin will not work unless you have global change permissions for the object type. I don't know if it is possible to override this or not.

I would have thought that the semantics should be that once you have global change permissions, you can change *any* object regardless of what the object level permissions. So checking for object level permissions become redundant.

The fact that `user.has_perms(...)` doesn't appear to check global permissions would appear to be a bug, not a feature IMHO.

It appears that django-guardian doesn't actually define semantics for how global permissions are used. It is unfortunate, as the current situation IMHO is a bit confusing. With changes like that discussed in #325 the default appear to be heading more towards global permissions add to any object permissions.

You appear to want the semantics so that the global level permissions are ignored (accept for the admin interface) and only the object level permissions are used. This is an assumption that might be correct for your project, however I don't think this will always be correct for all projects.

**Comment by Sovetnikov** [comment]
@brianmay I think you misunderstood core problem that i described.

See this:
I have a django admin with installed guardian and support for object level permissions.
operator is the user with staff permissions (no superuser access).
I have two objects:
http://127.0.0.1:8080/admin/main/complex/4/ - operator has full access
http://127.0.0.1:8080/admin/main/complex/7/ - operator has no access at all, "Forbidden" message displayed when he opens the page

The problem reproduction:
1. operator opens url http://127.0.0.1:8080/admin/main/complex/7/ and gets "Forbidden" message
2. operator opens URL http://127.0.0.1:8080/admin/main/complex/7/permissions/ - and see the managing permission page for complex 7.
3. operator adds all available permissions to himself for complex 7 (add, delete, change, etc)
4. operator opens url http://127.0.0.1:8080/admin/main/complex/7/, and has access to object complex 7 (like complex 4)

The problem itself: how i can disable step 2 and 3 for operator?

**Comment by brianmay** [comment]
@Sovetnikov The problem as you describe it above seems to be that the changing the object requires global change permission, however changing the object permissions requires no permissions at all - except maybe the user needs to be logged in, and I think they need staff access.

So the solution would seem to be that we should not allow changing object permissions unless the user has global change permissions too, and make it consistent with the permission checks already in django admin.

Does this make sense to you?

**Comment by Sovetnikov** [comment]
"changing the object permissions requires no permissions at all" - that's the problem!
global change permission check is suitable

**Comment by lukaszb** [comment]
Just to chime in: I don't see app example that would break, I am not aware of any. I just can imagine there are some in existence. But I can agree that if we make admin more strict with a version bump people would understand this.

Anyway, I agree with @Sovetnikov - before we allow staff users to change object level permissions for particular object we should check if that user has global permission to change that object type.

I also agree that allowing users to enter admin panel without trusting them in the first place is rather bad idea but we should follow Django approach here: staff members are not able to do anything before any permissions is given to them explicitly.

**Comment by brianmay** [comment]
Sounds reasonable to me. Now that I understand the problem, I consider this a bug, possible a security issue (it looks like the user shouldn't have access to change anything but they do), so should get fixed ASAP.

I will have a look at it now, although no guarantees when I will have a working solution.

**Comment by brianmay** [comment]
Hopefully this should be resolved now...
