### ISSUE TITLE
user.has_perm accepts anything instead of an object without raising an exception

### ISSUE THREAD

**Issue by mcgeeco** [django-guardian/django-guardian#314]
Noticed a bug in our software where we were passing an id (int) to has_perm instead of the object. I would have expected that to raise an exception but instead it returns False. It seems to return False for anything you throw at it - strings, booleans, etc. Took a quick look at the code but I can't immediately see how that could happen. Maybe it's actually a Django issue? Or is this intended behaviour? Let me know if I can help fix it if it's a problem here.

Thanks for all the hard work!

**Comment by brianmay** [comment]
This doesn't appear to be a bug. In a duck typing system like Python, strings, booleans, etc are all objects, and this is the expected behavior. We get a list of available permissions, and check if the required permission is in the list.

Suspect what you want is something like typing hints, see: 
https://docs.python.org/3/library/typing.html

For now, closing.
