### ISSUE TITLE
User.is_anonymous unexpected behavior for AnonymousUser

### ISSUE THREAD

**Issue by ryuusenshi** [django-guardian/django-guardian#331]
Introducing the concept of the ``AnonymousUser`` as yet another object of the ``User`` model corrupts the behavior of its ``is_anonymous()`` method, which now returns False for the ``AnonymousUser`` object. This is not in line with the expected return value for this method.

An example of this is:
```python
from guardian.compat import get_user_model

User = get_user_model()
anon = User.get_anonymous()
anon.is_anonymous()   # returns False
```

**Comment by brianmay** [comment]
Yes, this does seem surprising. However, I think there are only two solutions:

1. Change the way anonymous users are represented. Suspect this is not going to be easy. OR
2. Add this to the documentation so it is less surprising.

**Comment by ryuusenshi** [comment]
Couldn't we instead patch the User model in ``__init__`` to return the correct values::

```python
setattr(User, 'is_anonymous', lambda self: self.username==guardian_settings.ANONYMOUS_USER_NAME)
setattr(User, 'is_authenticated', lambda self: not self.username==guardian_settings.ANONYMOUS_USER_NAME)
```

**Comment by brianmay** [comment]
I don't like to change the meaning of the built in operators like this. As strictly speaking the Guardian anonymous user is a different thing to what Django considers the anonymous user. Maybe it was a mistake calling them them the same thing.

In fact, as a concrete example, if I look at the Django code, I see things like:

```
    def get_all_permissions(self, user_obj, obj=None):
        if not user_obj.is_active or user_obj.is_anonymous() or obj is not None:
            return set()
        if not hasattr(user_obj, '_perm_cache'):
            user_obj._perm_cache = self.get_user_permissions(user_obj)
            user_obj._perm_cache.update(self.get_group_permissions(user_obj))
        return user_obj._perm_cache
```

The assumption clearly is that Django anonymous users don't have any permissions. However this is not the case for Guardian anonymous users which were created precisely so that they could have permissions.

If you want to do this in your application that is fine, however just be warned that it might have consequences that you haven't considered.

**Comment by ryuusenshi** [comment]
Right. Sorry, Brian. For some reason I have ended up convincing myself that guardian replaced the ``AnonymousUser`` object set in ``request.user`` by the ``auth`` middleware, which would have meant that unexpected behavior could have resulted in unexpected consequences in 3rd party apps.
