### ISSUE TITLE
Remove support of django version less then 1.7

### ISSUE THREAD

**Issue by auvipy** [django-guardian/django-guardian#350]

**Comment by gabn88** [comment]
+1

**Comment by brianmay** [comment]
This would certainly simplify some things. Can remove silly conditionals for Django < 1.7. Always a bit nervous making changes that I am going to break support for old Django versions - which may or may not get picked up by tests.

**Comment by troygrosfield** [comment]
+1

**Comment by brianmay** [comment]
Looks like my change to fix #302 broke Django 1.2, Django 1.3, and Django 1.4 support.

https://travis-ci.org/django-guardian/django-guardian/builds/91051753

I could fix it; but think I will disable Django < 1.5 support instead, as the first step towards solving this.

**Comment by brianmay** [comment]
Django <1.5 support gone. 35f631491ad5567b0bfc32d5a3d9fd6fcf46b60c

docs/overview.rst still has a reference to Django 1.2, this should perhaps be updated at some stage.

**Comment by auvipy** [comment]
cool

**Comment by swistakm** [comment]
@brianmay it's a good policy to drop support for obsolete versions of software to push others to new releases but you should rethink if it's good to do such things in a point (patch) release.

If you keep such approach then you force other devs to stick to exact versions of such package (like `==1.3.1`) instead of being able to have more elastic dependency specs (like `<1.4.0,>=1.3.0`). Now I think some of people's builds are broken just because they do not expect backwards incompatible changes in point releases what that seems to be a *de facto* standard in python community. Also forcing us to use such strict dependency requirements in other packages "just for safety" makes us less eager to update dependencies. 

One of such broken packages is django-userena that still maintains `django 1.4` support in its `django-userena 1.4.x` branch. Now it can't take advantage of other fixes included in guardian's 1.3.2 version without breaking a contract of still supporting django1.4 on that branch.

**Comment by brianmay** [comment]
There are two seperate issues here:

# Why not a new major release?

My strategy generally is to create a new major version if there are changes that break the API that applications may be using. To the best of my knowledge there are no changes to the API in Guardian. It will still work with applications using the same API as before.

Possible `setup.py` should be modified to depend on Django >= 1.5; unfortunately this is something that pip doesn't support properly, so it may not help with your specific problem.

# Why drop support for older Djangos?

For starters, read this bug report. Supporting older versions of Django adds complexity to the project, complexity that is likely to lead to bugs. This project is maintained by unpaid volunteers, it is not in our best interests to keep old depreciated code around.

You seem to be upset that Django-Guardian no longer supports Django 1.4 because of a contract you have to support 1.4 - unfortunately this is not something I can be responsible for. The extended support for Django 1.4 ended at the start of October.  These dates, I believe were published well in advance too. I would never have agreed to any contract to maintain a project that uses a dead and no-longer maintained Django version. Who knows what security issues might pop up.

**Comment by auvipy** [comment]
@brianmay  +1

**Comment by swistakm** [comment]
Yeah I read whole thread (before writing). I is not so long. I completely understand your points. I even understood them before your reply and I thought that the first paragraph of my comment states that. But I do not feel offended that you have explained me this in sections with headers. Sorry if I was not clear enough with that but **I am completely for dropping the support for django1.4**. 

Anyway, I just pointed that there are some other approaches for marking such changes with arbitrary point numbers that you may consider in future (like using minor or major number). Currently nothing can be done about that because what has been done should not be undone. But in future when django-guardian will be dropping support for next django releases (it will, eventually) you may want to consider different approach.

It doesn't matter I feel upset or not. It even does not matter how django-userena will handle that or if I am responsible for that project. I wanted just to give at least one real life example of project that really depends on django-guardian and would definitely benefit from different approach to **numbering the changes** that drop support for some framework branch.

Take this only as a friendly information from fellow unpaid volunteer developers from different project that wanted to say: 

> We saw what you did there with recent update. We like it very much. We are very excited about the idea. But could you handle such changes by different part of version number in future? Seems like a very little effort for you that would make our (and possibly someone else's too) life easier and world simpler.

**Comment by carltongibson** [comment]
Using software beyond EOL is "at your own expense". Having to pin to a specific version is just a part of that. It ain't hard.

**Comment by brianmay** [comment]
Just for the record, headers were just so I could lay out my thoughts in a coherent manner, and weren't intended to offend. Second level headings might have been better, will see if I can fix that.

**Comment by brianmay** [comment]
If we drop support for Django < 1.7, do we drop the south migrations?

The more I think about it, the more I think we should. Otherwise we end up shipping untested, unused, and potentially broken code.

Do the south migrations as written even work? I seem to remember closing a number of bugs with the south migrations. Might be corner cases which fail. Am assuming that they mostly work for the remainder of this comment. If they are completely broken, we probably should just drop them.

*If* however there are sites still using Django < 1.7 *and* not on the latest south migration, maybe we need to document (e.g. by providing a script) the procedure on how to upgrade from south migrations to Django 1.7 style migrations (which basically would mean installing Django 1.6.x and django-guardian 1.3.2 into virtualenv and running migrations there) There is a script provided with Django in Debian that can be used as a template in fact:

http://anonscm.debian.org/cgit/python-modules/packages/python-django.git/tree/debian/contrib/migrate-south

Because dropping support for south migrations is a very significant change that will break *upgrades* of databases from old installs, it might actually be justified here to release it as 1.4.0, as per @swistakm suggestion.

This will enable the documentation to say "install the latest 1.3.x version for running Django South migrations", which in turn would allow for releasing newer 1.3.x versions if something was found to be broken with the south migrations and required urgent fixing.

**Comment by troygrosfield** [comment]
My understanding is south is now an obsolete project now that it's core is [included in django](https://docs.djangoproject.com/en/1.9/topics/migrations/) and has been for awhile now.  It's main page for South no longer even loads:

- http://south.aeracode.org/

+1 for removing support with a major version bump.  Why not version 2.0 since that would indicate a major release with breaking changes?

**Comment by Wtower** [comment]
I totally agree with @swistakm that supporting modules for a platform after its EOL makes little sense. And I also agree (in principle) with @carltongibson that if you have to support eg a project that runs on Django 1.4 then you inevitably will have to face such issues on your own. 

I am sure though that in such cases the community will try to help, but mostly any maintenance will have to be made by whoever supports such projects. Having said that, on the other hand, I got absolutely no clue how many people there are in this position, and this makes difference.

In my humble personal opinion, I don't think we should even maintain 1.7, since this is beyond EOL too. But probably it is an easy to maintain version.

Regarding south, the same applies, in agreement with @troygrosfield . Off with it. It has been great to have back then but its purpose is fulfilled. The world goes forward.

What is really the issue here though is the versioning of the project. I don't mind with what we have, but I needed to dig a bit in order to find which version requires what. We don't necessarily need to change versioning numvers, just a place to write down that.

**Comment by auvipy** [comment]
django rest framework now supports only django 1.7+ and one of my pull  req was accepted to remove obsolete south migrations from drf a few days ago!!

**Comment by brianmay** [comment]
Just went ahead and did this. Seems to still pass the tests...

Possibly more simplifications are possible, especially with guardian/compat.py

Guessing that `import_string` and `create_permissions` should get removed from this file for example.

**Comment by brianmay** [comment]
I think it is possible to overthink the version number thing. I note the documentation previously said:

* We support Django 1.5+, however next big ``guardian`` release (v2.0) we would
  support Django 1.7+ (or higher, depending on the date guardian v2.0 would be
  released). This is due to many simplifications in code we could do.

I don't particular care. Am thinking of just going to 1.4.0, as that enables as to produce 1.3.3 if ever required to fix south problems (I doubt this will ever happen actually).

**Comment by troygrosfield** [comment]
People will figure it out. Technically django doesn't follow the correct release versioning either as almost all "minor" version bumps have breaking changes.  Minor version bump works for me.

**Comment by auvipy** [comment]
@troygrosfield django minor version bump don't have any API breaking changes.
