### ISSUE TITLE
django-guardian.readthedocs.org defaults to v1.2

### ISSUE THREAD

**Issue by michael-k** [django-guardian/django-guardian#355]
Issues with django-guardian @ readthedocs:

- https://django-guardian.readthedocs.org forwards to https://django-guardian.readthedocs.org/en/v1.2/ instead of v..3.1
- https://django-guardian.readthedocs.org/en/stable/ references v1.3 instead of v1.3.1

**Comment by brianmay** [comment]
Looks like 1.3.1 was never actually tagged, so readthedocs doesn't know about it. This also confused me, I thought 1.3.1 wasn't released. Oops.

I have changed https://django-guardian.readthedocs.org/ to point to the latest stable version. So this should be fixed.

I also note a number of versions are marked as readthedocs are marked as inactive, including 1.3. Will change it so that the latest 1.x is active, so I will enable 1.3, 1.2.5, and disable 1.2

**Comment by brianmay** [comment]
Ok, I think this is all fixed now.
