### ISSUE TITLE
any plans to incorporate postgresql's 9.5 RLS?

### ISSUE THREAD

**Issue by dPeS** [django-guardian/django-guardian#368]
I know that it will be difficult to change connection (set role) in django, but from mass scale backends this could be needed in future.

https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#Row-Level_Security_Policies

any thoughts on this?

**Comment by brianmay** [comment]
Is it possible to use RLS with the existing DB schema?

I can't help but think (correct me if I am wrong) that a good solution for RLS would be Postgresql specific and look very different to django-guardian, and perhaps better suited for an independent project.

However my understanding of RLS is weak, and I don't really understand what it is capable of.

Any help?

**Comment by dPeS** [comment]
Yes, I was wonder if you are interested in such enhancement , but if most use cases are not heavy loaded then I totally understand.

**Comment by auvipy** [comment]
this could be a part of django.contrib.postgres

**Comment by brianmay** [comment]
@dPeS, I can't speak on behave of the other users and what work loads that may or may not have.

My initial impression of RLS is that this is a very different direction of development to the direction guardian is headed.

... and yes possibly change is a good thing.

However in this case the changes would be Postgresql specific. While it could be argued that Postgresql is the best database available for Django, many people use other databases, and I don't think we should be making guardian Postgresql specific.

Another option is that we have Postgresql specific code in Guardian. The key question is how much Postgresql specific code would we need? If the majority of Guardian needs to be replaced with conditional code, this is going to get very messy very quickly, and it would be better just to create a new project (maybe forked from Guardian) to handle this case.

Yet another option is to have some sort of abstraction layer in front of Guardian or your Postgresql specific code, that automatically detects which one to use. Creating a separate project would be the first step towards this goal. Could be risky: Design the code to work with Postgresql and suddenly find that people get access to unauthorized data because you were relying on server side checks that aren't present in other databases. Don't let me stop you from trying however.

I would suggest that if RLS can somehow use the existing Guardian DB models for server side permission checking, there might be a case to integrate it into Guardian.

If RLS cannot use the existing DB models, then it doesn't have anything in common with Guardian (except maybe API - and that can be duplicated), and a separate project - at least initially as a proof of concept thing - would be better.

**Comment by brianmay** [comment]
I think this sounds like a really good idea.

Regardless, I am going to close this issue for now - because it sounds like:

* It should be a separate project to django-guardian. At least initially as proof of concept. AND
* We don't have anybody prepared to put any effort into this right now.

(separate project could also mean fork of django-guardian too)

I have made this conclusion based on the lack of response to my previous email. If I am wrong on either point, then this issue can be reopened.
