### ISSUE TITLE
Runtime warning shouldn't display for anonymous_user_id setting when set to None

### ISSUE THREAD

**Issue by bzmwillemsen** [django-guardian/django-guardian#393]
```
?: (guardian.W002) No anonymous user ID is defined. Guardian supports anonymous user object permissions, therefore this needs to be specified in settings: `ANONYMOUS_USER_ID = -1`.
```

This error shows up if `ANONYMOUS_USER_ID = None`
But in the documentation if it's set to `None` then I am disabling the anonymous user object permissions.

This warning shouldn't show if its set to None.

Looks like this was introduced here: https://github.com/django-guardian/django-guardian/commit/0991c488d7f22fe72ad8bb53ca9c13431858cb67

**Comment by brianmay** [comment]
I think it has always been like this.

From the very first commit:

```patch
diff --git a/guardian/conf/settings.py b/guardian/conf/settings.py
new file mode 100644
index 0000000..dc1e4db
--- /dev/null
+++ b/guardian/conf/settings.py
@@ -0,0 +1,9 @@
+from django.conf import settings
+from django.core.exceptions import ImproperlyConfigured
+
+ANONYMOUS_USER_ID = getattr(settings, 'ANONYMOUS_USER_ID', None)
+if ANONYMOUS_USER_ID is None:
+    raise ImproperlyConfigured("In order to use django-guardian's "
+        "ObjectPermissionBackend authorization backend you have to configure "
+        "ANONYMOUS_USER_ID at your settings module")
+
```

I suspect the documentation is wrong.

Having said that, I don't like the ``ANONYMOUS_USER_ID`` mechanism. I would think it would be better to create and retrieve the anonymous use by ``ANONYMOUS_DEFAULT_USERNAME_VALUE`` (maybe rename the setting too) and discard all references to  ``ANONYMOUS_USER_ID``.  This in turn would solve #158 by letting the database pick the most appropriate id for the object instead of forcing it to use a hard coded value.

**Comment by bzmwillemsen** [comment]
I wasn't getting this warning message when I was on version 1.3.1, only after I upgraded to 1.4.1 recently.

**Comment by brianmay** [comment]
That is very odd that it was working for you, that fatal error - as annoying as it is - has not changed since the initial commit.
