### ISSUE TITLE
user.has_perm("perm", obj) behaves unexpectedly

### ISSUE THREAD

**Issue by Dzejkob** [django-guardian/django-guardian#49]
If I use standard `user.has_perm("perm")` method, then it will return `True` only, if user has a global permission `"perm"`.
And if `user.has_perm("perm", obj)` is used, it'll teturn `True` if user have permission to access this particular object.
But it will return `False`, even if user has a global permission `"perm"`, which is quite unexpected for me, because I assume, that having global permission should give user access to all objects. Am I right?

**Comment by xoen** [comment]
Hello, I found this issue as I'm trying jango-guardian and I found this behaviour buggy/very confusing.

I added a global permission (let's call it `view_user`) to a user (let's call it `joe`) and then checked if Joe can view a specific user (let's call it `other_user`) and surprisingly it returned `False`.

```python
joe = User.objects.get(username="joe")
other_user = User.objects.get(username="other_user")
assign_perm("myapp.view_user", joe)
joe.has_perm("myapp.view_user") # True as expected
joe.has_perm("myapp.view_user", other_user) # False, whaaaat?
```

Now, I'm not using the `permission_required` decorator explicitly as my view sets are "automatically" checking the permissions because of my `REST_FRAMEWORK/DEFAULT_PERMISSION_CLASSES` and `AUTHENTICATION_BACKENDS` in `settings.py`. How do I tell guardian to behave as expected then?

(Apologies if I'm missing something really stupid, this is kind of day 2/3 in djangoland)

**Comment by xoen** [comment]
Sorry for the noise today, even more interesting/confusing that [`guardian.shortcuts.get_objects_for_user()`](http://django-guardian.readthedocs.io/en/stable/api/guardian.shortcuts.html#std:shortcut-get_objects_for_user) honours the auth/global permissions by default (`accept_global_perms`).

```
accept_global_perms: if True takes global permissions into account. 
[...]
Default is True.
```

**Comment by doganmeh** [comment]
Although, this issue was closed in favor of another, there are a lot of insights here, so I am writing here to re-stir the conversation. Zen of the Python says: 

> There need to be one --and preferably only one-- obvious way to do it.

And to me that is to _fallback to global when local (object level) fails_. The order does not change the result (since Django `returns False if obj is not None`), but may change the performance. 

I do agree that having double checks all over the code is not a good design, and in some sense against the DRY principle too. However, guardian implementing functionality that is available within Django default backend is not DRY either. That Django allowing multiple backends, and checking one by one in order indicates that backends are supposed to play together, not replace one another. If this is right,then Django refusing to check globals when an `obj is not None` is _wrong_. 

I think we should open a ticket with Django, asking whether, and how, authorization backends play with each other, and go from there.

**Comment by doganmeh** [comment]
With that being said, I think Django changing its behavior is quite unlikely (although I do still think we should ask), so the status quo indicates that, guardian needs to evolve to be able to provide both depending upon which one is desired (which might be set either via settings or an argument to the function). But the default behavior I think should be the local fallback to global when false.

**Comment by doganmeh** [comment]
I would rather love it if Django preferred a tri-state permission system: True, False, and None. In that case, local checkers could _override_ the globals, and via `None` each backend could get to say: "I don't know it, ask the next in line". In that case, Django would stop checking after getting a `False` in one of the backends, and stop wasting processing power.

**Comment by airstandley** [comment]
@doganmeh Django does implement a tri-state permissions system (at least as of 1.10). The options are True, None, and raising PermissionDenied. Doing the later will cause Django to stop checking and return False.

As to the issue at hand, I believe it is a Contrib.Auth issue. That is the backend that deals with 'global permissions'. The problem is that they have established an indirect convention that has_perm with obj=None only checks 'table permissions' and has_perm with obj only checks 'row permissions'. They are unlikely to change that, but _should_ be open to extending their API to support checking both.

(At least I would hope they would be open to adding behavior to check both. It seems a clear flaw in their system.)

What would be your suggestions for the 'check both' API? The best I can think of is a kwarg.

**Comment by doganmeh** [comment]
I was talking about an explicitly tristate system where there would be a NullBooleanField on the Permission table. True, you take the lack of `True` (or lack of the permission) as a `None`. In that case permissions not specified by guardian should be taken as `None` not `False` like it is now, and the decision should be delegated to the global.

**Comment by doganmeh** [comment]
@airstandley I guess you mean an addition of a kwarg to `user.has_perm` such as:

`
def has_perm(self, perm, obj=None, fallback=False)
`

I think that would help.  In that case when `fallback=True` guardian would call Django backend and return the global. If I had a choice, though, I would prefer the fallback to Django be naturally handled by the framework, not by hijacking its internals.

**Comment by airstandley** [comment]
@doganmeh Sorry I misspoke. That should have read "True, **False**, and raising PermissionDenied". Not:
> The options are True, None, and raising PermissionDenied
The later is how I think of the returns in my head...

I think I may have also misunderstood what you meant by 
>I would rather love it if Django preferred a tri-state permission system
To clarify, you were talking about the Permission Model implementation specifically and not the system as a whole? 

My point was that the auth backend system does allow the exact short-cutting you described (At least for the `has_perm`, `has_module_perms` api). It is explicit, if not straightforward:
Any backend can either make a decision itself (return True or PermissionDenied), or delegate the decision to the next backed in the chain (return False). That is an implementation specific decision, and not a quality of the system itself.

An explicit ObjectPermissionBackend would be an issue for my project, so I would choose not to be explicit. ("Explicitness" makes integration with other permission checking backends cumbersome.) I suspect that, like you, others would prefer it be explicit. So having the 'explicitness' as setting makes sense to me.

**Comment by airstandley** [comment]
@doganmeh 
So about the kwarg.

First off I keep worrying we are not on the same page as to how the behaviour of auth's backend system was intended to work. So to be clear:
My understanding is that the intention was that backends work together. If an app wanted to use auth's Permission system (ie 'global permissions', although technically they would be 'table permissions' but potatoe, potato) it would install the auth ModelBackend in AUTH_BACKENDS. If that app wanted to use guardian's ObjectPermission system (ie 'row permission') it would isntall guardian's ObjectPermissionBackend in AUTH_BACKENDS. 
ModelBackend would handle global permission.
ObjectPermissionBackend would handle object permissions.
if a user only had an object permission, ModelBackend would never return True for `has_perm`. If a user only had a global permission ObjectPermissionBackend would never return True for `has_perm`. In  both cases a call to user.has_perm(perm, obj) should still return true, as the user does have the permission for _one_ of the installed backends. (This is were we hit a problem because ModelBackend fails on this account)

Ok so given all that.

In an ideal world where compatibility was not an issue, I too would prefer a simple change to contrib.auth's ModelBackend. `ModelBackend.has_perm(user_obj, perm, obj=None)` should return True if the user has the 'global permission' specified by  perm; regardless of whether obj is None or not.

However compatibility is an issue, which is why if you had a proposed solution to that issue.

The only _backwards compatible_ solution I can think of would be to add a kwarg to the API. Let's call it `obj_shortcut` because that's the best I can come up with off the top of my head. `object_shortcut` would default to True. If `object_shortcut` is True then backends should behave as the ModelBackend does now: they should _only_ check 'table/global' permissions if obj is None, otherwise they should _only_ check 'row/object' permissions. However if 'object_shortcut` is False then backends should behave as we would both prefer: they would check _both_ global and object permissions when object was not None. Then add-ons like Guardian could always supply a mixin with a `has_perm` method with `object_shortcut=False` as the default.

`user.has_perm(perm, obj, object_shortcut=False) would correctly return True if the Permission represented by perm was assigned to User, while legacy calls to user.has_perm(perm, obj) would continue to return False.

**Comment by doganmeh** [comment]
@airstandley You are right, `False` or `None` does not matter. They both mean **I don't know**. Eventually if no one knows, permission is not granted. 

I am generally on the same page with you, although django forcing backends to behave one way or another seems to degrade loosely coupledness. I think it should have mechanisms to allow each backend get the information they needed to get their jobs done. I am with you on the keyword argument(s) though, but not just forcing one way or another. 

This conversation seems like a waste of time, but it helped me clarify to myself that there is not permission granted in guardian is not a denial, it is just lack of information. 

Anyways, I made a pull request #546. Please check it out and let me know what you think.

**Comment by doganmeh** [comment]
I created a ticket with django: https://code.djangoproject.com/ticket/29012, and wonder what would they say.

**Comment by doganmeh** [comment]
Seems there were some other tickets with django: https://code.djangoproject.com/ticket/20218

I closed mine.

**Comment by airstandley** [comment]
@doganmeh 
I like the direction you are headed with #546. If it would help, I should have time to look over the rest of the units and write some tests for these fallbacks this weekend.

On a tangent. Your comment about "Django forcing backends" to behave a specific way confuses me, but it also gave me a thought. Backends can behave however they would like; my initial concern about Guardian's ObjectPermissionBackend stems from the documentation suggesting it was designed to run alongside Auth's ModelBackend. Guardian could offer multiple backends, one designed to work with ModelBackend, and one designed to work alone. (I.E. one that just checks Guardian's UserObjectPermission/GroupObjectPermission tables, the other checks both UserObjectPermission/GroupObjectPermission tables and Auth's Permission table.)
Personally I prefer the current approach with a setting and kwargs. I think the major downside to a multiple backend approach would be that it becomes unclear how the short-cuts and convenience functions should behave.

**Comment by airstandley** [comment]
Saw the post to the Django dev mailing list. I hope they accept that, or agree to change the behaviour in an incompatible way. The current limitation on the API is just clunky.

**Comment by doganmeh** [comment]
After dealing with this issue for about a week now, I came to more firmly believe that each backend needs to do just one thing, which is object permissions for Guardian. For that to happen Django must treat `obj`s more nicely. 

Here is the patch I sent to Django for that: https://github.com/django/django/pull/9581. Your feedbacks/support would be appreciated. 

Ones that makes it in, we can clean up retrieval of model permissions whereever there is in Guardian, and just make a call to the default backend.
