### ISSUE TITLE
Guardian system check for AUTHENTICATION_BACKENDS is unnecessary if using a custom auth backend

### ISSUE THREAD

**Issue by viseshrp** [django-guardian/django-guardian#639]
Hi,
So while using guardian in a project, due to specific requirements, I had to create my own auth backend for object permissions(I used guardian's `ObjectPermissionChecker` inside it). So I had no use for `guardian.backends.ObjectPermissionBackend`. 
When system checks looks at this, it does not see the exact string and throws a warning, which also shows up in the logs for no reason. Ref: https://github.com/django-guardian/django-guardian/blob/devel/guardian/checks.py#L14

There's a workaround: https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SILENCED_SYSTEM_CHECKS

As an alternative, I propose to add an option in settings like `GUARDIAN_CUSTOM_BACKEND = True` and perform the check based on this setting. Not sure if its overkill, but I could do a PR if that's acceptable.

**Comment by ad-m** [comment]
Do I understand correctly that you propose to introduce a configuration parameter in django-guardian ```GUARDIAN_CUSTOM_BACKEND``` whose operation will be identical to a generic solution built into Django based on a configuration parameter ```SILENCED_SYSTEM_CHECKS```?
Do you expect something more from the new parameter than "permanently acknowledge and ignore" and warning "not be output to the console"?

I asks, because I would like to understand expectations well. Currently, I see no reason to repeat the mechanisms in django-guardian that are built into django. Therefore, a good understanding of your expectations is critical to the satisfaction of handling your inquiry.

**Comment by viseshrp** [comment]
Yep, I hear you. It might be unnecessary to add a parameter just for this. Otherwise, this could be at least documented to direct people to use django's system check silencer if they ever hit my case. My original proposition was not aware of this django's internal setting, and after reading that, this proposed setting did not make sense to me either. Sorry about that. Closing.

**Comment by ad-m** [comment]
Any development of documentation through pull request is welcome :)
