### ISSUE TITLE
user should see only filtered list of object in admin listview

### ISSUE THREAD

**Issue by zbynekdrlik** [django-guardian/django-guardian#681]
I have list of devices(objects), which need be accessible for users in some group. In admin I am not be able setup permissions to logged user see only devices which are accessible to same group.
The objects are not owned by one group or one user. There can be many groups which should have access to one object.
Is it possible in guardian by default or there is necessary to override same functions?

**Comment by ad-m** [comment]
You need overwrite ```get_queryset```. Something like:

```python
from guardian.shortcuts import get_objects_for_user

class DeviceAdmin(GuardedModelAdmin):
...
    def get_queryset(self, request):
         return get_objects_for_user(user=request.user, perms='can_view', klass=self.model, use_groups=True)) 
```

Since Django 2.1 ( https://docs.djangoproject.com/en/2.1/releases/2.1/#model-view-permission ) there is ```view_*``` permission. so For this reason, a pull requests is welcome that will make that featur build-in (configurable accordingly for general use). Also consider the consistency with the Django project:

> The implementation is backwards compatible in that there isn't a need to assign the "view" permission to allow users who have the "change" permission to edit objects.

**Comment by zbynekdrlik** [comment]
Perfect it is working
```
    def get_queryset(self, request):
        return get_objects_for_user(user=request.user, perms='manage', klass=self.model, use_groups=True)

```
