### ISSUE TITLE
Broken when Custom groups in AbstractBaseUser

### ISSUE THREAD

**Issue by VaZark** [django-guardian/django-guardian#783]
**Setup** 

The django project uses an AbstractBaseUser along with a Custom group for permissions.

```python
class CustomGroup(Group):
    additional_field = models.CharField(max_length=10)
    ....

class CustomUser(AbstractBaseUser, PermissionsMixin):
    groups = models.ManyToManyField(CustomGroup)
    ....
```

**Error / Unexpected Behaviour**

When opening he django admin, we get the error `Cannot query "AnonymousUser": Must be "Group" instance.` 

A little bit of googling gives me the impression that `.has_perm()` function invokes the Group class directly and does not update itself to reflect the custom group classes defined in the user model

**Ideal Solution**

Django guardian should detect the `Group` model associated with the user model and use it for perms. Or mention a workaround in the docs

**Comment by VaZark** [comment]
The initial migration runs a foreign key to the Group model under auth automatically. 

` ('group', models.ForeignKey(to='auth.Group', on_delete=models.CASCADE)),` in 0001_initial.py

Can the string made into a swappable dependency or set by using a custom variable in settings ??

**Comment by michael-k** [comment]
See django-guardian/django-guardian#504

**Comment by BonaFideIT** [comment]
Here is a solution for custom groups: https://github.com/django-guardian/django-guardian/pull/825.

To solve this issue you mentioned above, we added a pull request to django core. Until it is not included in a release you can use this solution: https://github.com/django-guardian/django-guardian/pull/825#issuecomment-2380685148.

We will close this issue because there will be a fix in django core in the next release and we have a pending PR for the custom group support.
